<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Consubook - Confirmación de cuenta</title>
</head>
<body>

<div style="font-family: 'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif; text-align: center; font-size: 14px;">
	<div style="background-color: #1d9ce5; text-align: center; margin: 0; padding: 10px 0; margin-bottom: 10px;">
            <a href="<?=$this->config['application']['publicUrl'];?>" target="_blank"><img src="<?='http://i1212.photobucket.com/albums/cc449/angelfcm/logo-268x50_zps9frdtm1z.png';/*$this->config->application->publicUrl .'img/logo-268x50.png';*/ ?>" height="50" /></a>
    </div>
	<div style="padding: 10px; font-size: 20px;">
		Gracias por registrarte <b><?= $account->firstname; ?></b>!
	</div>
 	<div style="padding: 10px;">Resumen del registro:</div>
 	<center>
    <table style="margin: 10px auto; text-align: left; background-color: #eee; border: 1px solid #000; border-spacing: 10px; border-collapse: separate;" cell-spacing="10">
        <tr><td style="text-align: right"><strong>Nombre personal: </strong></td><td> <?= $account->firstname.' '.$account->lastname; ?></td></tr>
        <tr><td style="text-align: right"><strong>Nombre de usuario: </strong></td><td><?= $account->username; ?></td></tr>
        <tr><td style="text-align: right"><strong>Email: </strong></td><td><?= $account->email; ?></td></tr>
        <tr><td style="text-align: right"><strong>Fecha y hora: </strong></td><td><?= $account->created_at; ?></td></tr>
    </table>
    </center>
	<div style="padding: 10px; margin-bottom: 10px;">Para poder seguir utilizando tu cuenta, es necesario que confirmes tu correo electrónico presionando el siguiente botón: </div>
	<a href="<?= $this->config->application->publicUrl."/singup/confirmEmail/{$confirmation->code}"/*$this->url->get(array('for' => 'singup/confirmEmail', 'code' => $confirmatio->code));*/ ?>" >
		<div style="text-decoration: none; display: inline-block; background-color: #54b4eb; padding: 8px; color: #fff; text-align: center; cursor: pointer; font-size: 18px; border-radius: 3px;">Confirmar!</div>
	</a>
</div>

</body>
</html>