<main class="col-md-9 col-md-push-3">
	<h1>Bienvenido a Consubook!</h1>
</main>
<aside class="col-md-3 col-md-pull-9">
	<section class="panel panel-default">
		<header class="panel-heading" role="tab" id="headingCategories">
			<h1 class="panel-title"><a data-toggle="collapse" href="#collapseCategories">Categorías</a></h1>
		</header>
		<div class="panel-body panel-collapse collapse in" id="collapseCategories">
			<nav>
				<ul class="nav nav-pills nav-stacked">
					<?php foreach( $categories as $category ): ?>
						<li role="presentation"><a role="menuitem" tabindex="-1" href="<?=$this->url->get(array(
                'for'=>'search', 
                'filter' => 'category', 
                'query' => str_replace(' ', '+', $category->name))); ?>"><?= $category->name ;?>
						</a></li>
					<?php endforeach; ?>
				</ul>
			</nav>
		</div>
	</section>
</aside>