<form>
   	<div class="form-group">
    	<label for="singupPhone">Teléfono</label>
    	<input type="phone" class="form-control" id="singupPhone">
  	</div>
  	<div class="form-group">
    	<label for="singupEmail">E-mail</label>
    	<input type="email" class="form-control" id="singupEmail" placeholder="E-mail">
  	</div>
  	<div class="form-group">
    	<label for="singupPassword">Contraseña</label>
    	<input type="password" class="form-control" id="singupPassword" placeholder="Contraseña">
  	</div>
  	<div>
     	<label for="singupConfirmPassword">Confirmar contraseña</label>
    	<input type="password" class="form-control" id="singupConfirmPassword" placeholder="Password">
    </div>
  	<div class="form-group">
    	<label for="singupName">Nombre(s)</label>
    	<input type="email" class="form-control" id="singupName" placeholder="Enter email">
  	</div>
   	<div class="form-group">
    	<label for="singupLastname">Apellido</label>
    	<input type="email" class="form-control" id="singupLastname" placeholder="Enter email">
  	</div>
   	<div class="form-group">
    	<label for="singupGender">Sexo</label>
    	<select class="form-control" id="singupGender">
    		<option>Masculino</option>
    		<option>Femenino</option>
    	</select>
  	</div>
  	<div class="form-group">
  		<button type="submit" class="btn btn-primary">Crear cuenta</button>
  	</div>
</form>