<?php if ( isset($error['validation']) ) { foreach($error['validation'] as $error):?>
<ul class="danger">
  <li class="text-danger"><?= $error; ?></li>
</ul>
<?php endforeach; } ?>
<?= \Phalcon\Tag::Form('singup'); ?>
    <div class="form-group">
        <label for="singupUsername" class="control-label">Nombre de usuario</label>
        <input type="text" name="username" class="form-control" id="singupUsername" placeholder="Nombre de usuario" />
    </div>
  	<div class="form-group">
    	  <label for="singupEmail">E-mail</label>
    	  <input type="email" class="form-control" id="singupEmail" placeholder="E-mail" />
  	</div>
  	<div class="form-group">
        <div class="row">
            <div class="col-sm-6">  
    	          <label for="singupPassword">Contraseña</label>
    	          <input type="password" class="form-control" id="singupPassword" placeholder="Contraseña" />
            </div>
            <div class="col-sm-6"> 
         	      <label for="singupConfirmPassword">Confirmar contraseña</label>
        	      <input type="password" class="form-control" id="singupConfirmPassword" placeholder="" />
            </div>
        </div>
    </div>
  	<div class="form-group">
        <div class="row">
            <div class="col-sm-6"> 
                <label for="singupName">Nombre</label>
    	          <input type="email" class="form-control" id="singupName" placeholder="" />
            </div>
            <div class="col-sm-6"> 
                <label for="singupLastname">Apellidos</label>
    	          <input type="email" class="form-control" id="singupLastname" placeholder="" />
            </div>
        </div>
  	</div>
   	<div class="form-group">
        <label for="singupGender">Sexo</label>
    	  <select class="selectpicker" id="singupGender">
    		    <option>Masculino</option>
    		    <option>Femenino</option>
    	  </select>
  	</div>
    <div class="form-group">
        <label for="singupPhone">Teléfono</label>
        <input type="phone" class="form-control" id="singupPhone" />
    </div>
  	<div class="form-group">
  		   <button type="submit" class="btn btn-primary">Crear cuenta</button>
  	</div>
</form>