<div class="jumbotron alert-success">
	<h1>Felicidades tu cuenta ha sido creada!</h1>
	<p>
	Ahora puedes solicitar préstamos, revisar tu cuenta, actualizar tu información personal y de perfil, entre otras cosas más.
	</p>
	<p>
	Para conservar tu cuenta hemos envíado un correo electrónico al email que nos proporcionaste para que puedas confirmar tu cuenta.
	</p>
	<a class="btn btn-primary btn-lg" role="button" href="<?php echo $this->url->get('/'); ?>">Ir a la página inicial</a>
	</p>
</div>